### ISSUE TITLE
Inconsistent Server Status

### ISSUE THREAD

**Issue by ersignee** [the-hideout/tarkov-api#136] opened 2023-01-27 10:50 UTC
Don't know why this happens, but when running the bot with this request:
```
`'''
            query {
                status {
                    currentStatuses {
                        name
                        message
                        statusCode
                    }
                }
            }'''`
```
from Europe it returns General Server Status as well as in detail statuses, such as website, matchmaking etc... but when running this command from the USA this returns just the Genereal Server Status.
Look at this:
![image](https://user-images.githubusercontent.com/61605346/215068144-68cdc758-1f5b-4743-ab3f-c8dbd18d5bf0.png)
I run the first command in Europe and the second command from a server in the USA, and this is the difference. It's not a coding error, the problem is the site doesn't return the full dictionary of servers, but just the General one.
This is the difference from the server response from the USA servers:
```
`{
  "data": {
    "status": {
      "generalStatus": {
        "message": "N/A",
        "statusCode": "Unstable"
      },
      "currentStatuses": [
        {
          "message": "N/A",
          "statusCode": "Unstable",
          "name": "Global"
        }
      ]
    }
  }
}`
```
and from the EU servers:
```
{
  "data": {
    "status": {
      "generalStatus": {
        "message": "",
        "statusCode": "OK"
      },
      "currentStatuses": [
        {
          "message": null,
          "statusCode": "OK",
          "name": "Website"
        },
        {
          "message": null,
          "statusCode": "OK",
          "name": "Forum"
        },
        {
          "message": null,
          "statusCode": "OK",
          "name": "Authentication"
        },
        {
          "message": null,
          "statusCode": "OK",
          "name": "Launcher"
        },
        {
          "message": null,
          "statusCode": "OK",
          "name": "Group lobby"
        },
        {
          "message": null,
          "statusCode": "OK",
          "name": "Trading"
        },
        {
          "message": null,
          "statusCode": "OK",
          "name": "Matchmaking"
        },
        {
          "message": null,
          "statusCode": "OK",
          "name": "Friends and msg."
        },
        {
          "message": null,
          "statusCode": "OK",
          "name": "Inventory operations"
        },
        {
          "message": "",
          "statusCode": "OK",
          "name": "Global"
        }
      ]
    }
  }
}
```

**Comment by Razzmatazzz** [comment] 2023-02-17 17:53
We haven't been able to reproduce this. Can you confirm it is still happening?

**Comment by GrantBirki** [comment] 2023-03-23 22:09
@ersignee It looks like this issue was opened quite some time ago. Can you confirm if this is still happening? Otherwise we will close this for now

**Comment by ersignee** [comment] 2023-03-24 20:21
I had this issue at the time of writing it. Now it is 100% fixed

**Closed** 2023-03-24 20:27 UTC
